from __future__ import annotations

from typing import Callable

import numpy as np


# =============================================================================
# Type aliases
# =============================================================================

StateNonlinearity = Callable[[np.ndarray, np.ndarray], tuple[np.ndarray, np.ndarray]]

ReferenceNonlinearity = Callable[
    [np.ndarray, np.ndarray], tuple[np.ndarray, np.ndarray]
]


# =============================================================================
# Identity nonlinearities
# =============================================================================


def identity_nonlinearity(
    state: np.ndarray, derivative: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """
    Return the state and derivative without modification.

    Parameters
    ----------
    state : numpy.ndarray
        Current actuator state.

    derivative : numpy.ndarray
        Current state derivative.

    Returns
    -------
    state : numpy.ndarray
        Unmodified state.

    derivative : numpy.ndarray
        Unmodified derivative.
    """
    return state, derivative


def identity_reference_nonlinearity(
    reference: np.ndarray, memory: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """
    Return the reference without modification.

    Parameters
    ----------
    reference : numpy.ndarray
        Actuator reference signal.

    memory : numpy.ndarray
        Persistent reference-nonlinearity memory.

    Returns
    -------
    reference : numpy.ndarray
        Unmodified reference.

    memory : numpy.ndarray
        Unmodified memory.
    """
    return reference, memory


# =============================================================================
# Generic pipeline
# =============================================================================


def _compose_two_nonlinearities(
    first: StateNonlinearity, second: StateNonlinearity
) -> StateNonlinearity:
    """
    Compose two state nonlinearities.

    The second nonlinearity receives the output generated by the first one.

    Parameters
    ----------
    first : callable
        First state nonlinearity.

    second : callable
        Second state nonlinearity.

    Returns
    -------
    callable
        Composed state nonlinearity.
    """

    def composed(
        state: np.ndarray, derivative: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        state, derivative = first(state, derivative)
        state, derivative = second(state, derivative)

        return state, derivative

    return composed


def nonlinearities_pipeline_factory(
    *nonlinearities: StateNonlinearity,
) -> StateNonlinearity:
    """
    Create a pipeline of state nonlinearities.

    The nonlinearities are executed sequentially in the same order in which
    they are provided.

    Parameters
    ----------
    *nonlinearities : callable
        State nonlinearities to compose.

    Returns
    -------
    callable
        State-nonlinearity pipeline.

    Examples
    --------
    The following pipeline applies acceleration, velocity and position
    limitations in that order:

    >>> pipeline = nonlinearities_pipeline_factory(
    ...     acceleration_limiter_factory(100.0),
    ...     velocity_limiter_factory(10.0),
    ...     position_limiter_factory(1.0),
    ... )
    """

    if not nonlinearities:
        return identity_nonlinearity

    pipeline = nonlinearities[0]

    for nonlinearity in nonlinearities[1:]:
        pipeline = _compose_two_nonlinearities(pipeline, nonlinearity)

    return pipeline


# =============================================================================
# Backlash
# =============================================================================


def backlash_factory(backlash_width: float) -> ReferenceNonlinearity:
    """
    Create a hysteretic backlash nonlinearity.

    The backlash is modeled as a lost-motion band between the commanded
    reference and the effective actuator reference.

    The implementation has persistent memory. The memory contains the
    effective reference generated by the backlash model.

    ``backlash_width`` represents the total width of the lost-motion band.
    Therefore, the half-width used by the hysteresis model is:

    ``half_width = backlash_width / 2``.

    The model is:

    * If ``reference > output + half_width``, the output follows the reference
      minus the half-width.
    * If ``reference < output - half_width``, the output follows the reference
      plus the half-width.
    * Otherwise, the previous output is maintained.

    The persistent memory is stored in a NumPy array rather than a Python
    object. This allows the memory to be safely captured by Numba-compatible
    closures.

    Parameters
    ----------
    backlash_width : float
        Total backlash width in the same units as the actuator reference.

    Returns
    -------
    callable
        Reference nonlinearity implementing backlash.

    Raises
    ------
    ValueError
        If ``backlash_width`` is negative.

    Notes
    -----
    The returned function expects ``memory`` to be a one-element NumPy array.
    The array is modified in-place at every simulation step.

    Examples
    --------
    For a backlash width of 0.02 rad:

    >>> backlash = backlash_factory(0.02)
    >>> memory = np.zeros(1)
    """

    if backlash_width < 0.0:
        raise ValueError("backlash_width must be non-negative.")

    half_width = 0.5 * backlash_width

    def backlash(
        reference: np.ndarray, memory: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Apply hysteretic backlash to the reference.

        Parameters
        ----------
        reference : numpy.ndarray
            Requested actuator reference.

        memory : numpy.ndarray
            One-element array containing the persistent effective reference.

        Returns
        -------
        effective_reference : numpy.ndarray
            Reference after backlash.

        memory : numpy.ndarray
            Updated persistent memory.
        """

        reference_value = reference[0]
        output_value = memory[0]

        if reference_value > output_value + half_width:
            output_value = reference_value - half_width

        elif reference_value < output_value - half_width:
            output_value = reference_value + half_width

        memory[0] = output_value

        effective_reference = np.empty_like(reference)
        effective_reference[0] = output_value

        return effective_reference, memory

    return backlash


# =============================================================================
# Acceleration limiter
# =============================================================================


def acceleration_limiter_factory(maximum_acceleration: float) -> StateNonlinearity:
    """
    Create an acceleration limiter.

    Parameters
    ----------
    maximum_acceleration : float
        Maximum absolute acceleration.

    Returns
    -------
    callable
        Acceleration-limiting nonlinearity.

    Raises
    ------
    ValueError
        If ``maximum_acceleration`` is negative.
    """

    if maximum_acceleration < 0.0:
        raise ValueError("maximum_acceleration must be non-negative.")

    def acceleration_limiter(
        state: np.ndarray, derivative: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        limited_derivative = derivative.copy()

        limited_derivative[1] = np.clip(
            limited_derivative[1], -maximum_acceleration, maximum_acceleration
        )

        # The position derivative must remain equal to velocity.
        limited_derivative[0] = state[1]

        return state, limited_derivative

    return acceleration_limiter


# =============================================================================
# Velocity limiter
# =============================================================================


def velocity_limiter_factory(maximum_velocity: float) -> StateNonlinearity:
    """
    Create a velocity limiter.

    Parameters
    ----------
    maximum_velocity : float
        Maximum absolute velocity.

    Returns
    -------
    callable
        Velocity-limiting nonlinearity.

    Raises
    ------
    ValueError
        If ``maximum_velocity`` is negative.
    """

    if maximum_velocity < 0.0:
        raise ValueError("maximum_velocity must be non-negative.")

    def velocity_limiter(
        state: np.ndarray, derivative: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        limited_state = state.copy()
        limited_derivative = derivative.copy()

        velocity = np.clip(limited_state[1], -maximum_velocity, maximum_velocity)

        limited_state[1] = velocity

        # Position derivative must always be the actual limited velocity.
        limited_derivative[0] = velocity

        # Prevent acceleration from pushing velocity further outside the stop.
        if velocity >= maximum_velocity and limited_derivative[1] > 0.0:
            limited_derivative[1] = 0.0

        elif velocity <= -maximum_velocity and limited_derivative[1] < 0.0:
            limited_derivative[1] = 0.0

        return limited_state, limited_derivative

    return velocity_limiter


# =============================================================================
# Position limiter
# =============================================================================


def position_limiter_factory(maximum_position: float) -> StateNonlinearity:
    """
    Create a symmetric position limiter.

    Parameters
    ----------
    maximum_position : float
        Maximum absolute actuator position.

    Returns
    -------
    callable
        Position-limiting nonlinearity.

    Raises
    ------
    ValueError
        If ``maximum_position`` is negative.
    """

    if maximum_position < 0.0:
        raise ValueError("maximum_position must be non-negative.")

    def position_limiter(
        state: np.ndarray, derivative: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        limited_state = state.copy()
        limited_derivative = derivative.copy()

        position = limited_state[0]

        # Positive mechanical stop.
        if position >= maximum_position:
            limited_state[0] = maximum_position

            if limited_state[1] > 0.0:
                limited_state[1] = 0.0

            if limited_derivative[1] > 0.0:
                limited_derivative[1] = 0.0

        # Negative mechanical stop.
        elif position <= -maximum_position:
            limited_state[0] = -maximum_position

            if limited_state[1] < 0.0:
                limited_state[1] = 0.0

            if limited_derivative[1] < 0.0:
                limited_derivative[1] = 0.0

        limited_derivative[0] = limited_state[1]

        return limited_state, limited_derivative

    return position_limiter


# =============================================================================
# Velocity-dependent acceleration limiter
# =============================================================================


def velocity_dependent_acceleration_limiter_factory(
    velocity_lut: np.ndarray, acceleration_lut: np.ndarray
) -> StateNonlinearity:
    """
    Create an acceleration limiter dependent on actuator velocity.

    The maximum acceleration is obtained by linearly interpolating the
    acceleration lookup table using the absolute actuator velocity.

    Values outside the velocity lookup-table range use the acceleration
    value at the nearest endpoint.

    Parameters
    ----------
    velocity_lut : numpy.ndarray
        Strictly increasing velocity breakpoints. The values must be
        non-negative.

    acceleration_lut : numpy.ndarray
        Maximum absolute acceleration corresponding to each velocity
        breakpoint. All values must be non-negative.

    Returns
    -------
    callable
        Velocity-dependent acceleration-limiting nonlinearity.

    Raises
    ------
    ValueError
        If the lookup tables have different sizes.
    ValueError
        If fewer than two lookup-table points are provided.
    ValueError
        If the velocity lookup table is not strictly increasing.
    ValueError
        If the velocity lookup table contains negative values.
    ValueError
        If the acceleration lookup table contains negative values.
    """

    velocity_lut = np.asarray(velocity_lut, dtype=np.float64)
    acceleration_lut = np.asarray(acceleration_lut, dtype=np.float64)

    if velocity_lut.size != acceleration_lut.size:
        raise ValueError("velocity_lut and acceleration_lut must have the same size.")

    if velocity_lut.size < 2:
        raise ValueError(
            "velocity_lut and acceleration_lut must contain at least two points."
        )

    if np.any(velocity_lut < 0.0):
        raise ValueError("velocity_lut must contain only non-negative values.")

    if np.any(np.diff(velocity_lut) <= 0.0):
        raise ValueError("velocity_lut must be strictly increasing.")

    if np.any(acceleration_lut < 0.0):
        raise ValueError("acceleration_lut must contain only non-negative values.")

    def velocity_dependent_acceleration_limiter(
        state: np.ndarray, derivative: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Apply velocity-dependent acceleration limiting.

        Parameters
        ----------
        state : numpy.ndarray
            Current actuator state.

        derivative : numpy.ndarray
            Current state derivative.

        Returns
        -------
        state : numpy.ndarray
            Unmodified actuator state.

        derivative : numpy.ndarray
            Derivative with acceleration limited according to actuator
            velocity.
        """

        limited_derivative = derivative.copy()

        absolute_velocity = abs(state[1])

        maximum_acceleration = np.interp(
            absolute_velocity, velocity_lut, acceleration_lut
        )

        limited_derivative[1] = np.clip(
            limited_derivative[1], -maximum_acceleration, maximum_acceleration
        )

        # The position derivative must remain equal to velocity.
        limited_derivative[0] = state[1]

        return state, limited_derivative

    return velocity_dependent_acceleration_limiter


# =============================================================================
# YAML / dictionary builders
# =============================================================================


def _build_backlash(config: dict) -> ReferenceNonlinearity:
    """
    Build a backlash nonlinearity from a configuration dictionary.

    Parameters
    ----------
    config : dict
        Backlash configuration.

    Returns
    -------
    callable
        Configured backlash nonlinearity.
    """

    return backlash_factory(backlash_width=float(config["backlash_width"]))


def _build_acceleration_limiter(config: dict) -> StateNonlinearity:
    """
    Build an acceleration limiter from a configuration dictionary.
    """

    return acceleration_limiter_factory(
        maximum_acceleration=float(config["maximum_acceleration"])
    )


def _build_velocity_limiter(config: dict) -> StateNonlinearity:
    """
    Build a velocity limiter from a configuration dictionary.
    """

    return velocity_limiter_factory(maximum_velocity=float(config["maximum_velocity"]))


def _build_position_limiter(config: dict) -> StateNonlinearity:
    """
    Build a position limiter from a configuration dictionary.
    """

    return position_limiter_factory(maximum_position=float(config["maximum_position"]))


def _build_velocity_dependent_acceleration_limiter(config: dict) -> StateNonlinearity:
    """
    Build a velocity-dependent acceleration limiter from configuration.
    """

    return velocity_dependent_acceleration_limiter_factory(
        velocity_lut=np.asarray(config["velocity_lut"], dtype=np.float64),
        acceleration_lut=np.asarray(config["acceleration_lut"], dtype=np.float64),
    )


# =============================================================================
# Factory registry
# =============================================================================


REFERENCE_NONLINEARITY_FACTORIES = {"backlash": _build_backlash}


STATE_NONLINEARITY_FACTORIES = {
    "acceleration_limiter": _build_acceleration_limiter,
    "velocity_limiter": _build_velocity_limiter,
    "position_limiter": _build_position_limiter,
    "velocity_dependent_acceleration_limiter": (
        _build_velocity_dependent_acceleration_limiter
    ),
}


# =============================================================================
# Dictionary-based pipeline factory
# =============================================================================


def nonlinearities_pipeline_factory_from_dict(
    config: list[dict] | None,
) -> tuple[ReferenceNonlinearity | None, StateNonlinearity | None]:
    """
    Create reference and state nonlinearities from a configuration list.

    The YAML configuration can contain both reference nonlinearities and
    state nonlinearities in a single ``nonlinearities`` list.

    Reference nonlinearities, such as backlash, are separated from state
    nonlinearities and returned as independent pipelines.

    Parameters
    ----------
    config : list of dict, optional
        Nonlinearity configuration.

    Returns
    -------
    reference_nonlinearities : callable or None
        Pipeline applied to the actuator reference before integration.

    state_nonlinearities : callable or None
        Pipeline applied to the actuator state and derivative during
        integration.

    Raises
    ------
    ValueError
        If an unknown nonlinearity type is specified.

    Examples
    --------
    Given the following YAML configuration:

    .. code-block:: yaml

        nonlinearities:
          - type: backlash
            backlash_width: 0.001

          - type: velocity_dependent_acceleration_limiter
            velocity_lut: [0.0, 1.0, 2.0]
            acceleration_lut: [10.0, 8.0, 5.0]

          - type: velocity_limiter
            maximum_velocity: 2.0

          - type: position_limiter
            maximum_position: 0.01939

    the factory returns:

    ``(reference_pipeline, state_pipeline)``

    where backlash belongs to the reference pipeline and the three limiters
    belong to the state pipeline.

    Notes
    -----
    The order of nonlinearities within each category is preserved.

    Backlash memory is not created by this factory. The actuator solver owns
    the persistent memory and initializes it when necessary.
    """

    if not config:
        return None, None

    reference_nonlinearities = []
    state_nonlinearities = []

    for nonlinearity_config in config:
        if "type" not in nonlinearity_config:
            raise ValueError("Each nonlinearity configuration must contain 'type'.")

        nonlinearity_type = nonlinearity_config["type"]

        if nonlinearity_type in REFERENCE_NONLINEARITY_FACTORIES:
            factory = REFERENCE_NONLINEARITY_FACTORIES[nonlinearity_type]

            reference_nonlinearities.append(factory(nonlinearity_config))

        elif nonlinearity_type in STATE_NONLINEARITY_FACTORIES:
            factory = STATE_NONLINEARITY_FACTORIES[nonlinearity_type]

            state_nonlinearities.append(factory(nonlinearity_config))

        else:
            raise ValueError(f"Unknown nonlinearity type: {nonlinearity_type!r}")

    reference_pipeline = (
        nonlinearities_pipeline_factory(*reference_nonlinearities)
        if reference_nonlinearities
        else None
    )

    state_pipeline = (
        nonlinearities_pipeline_factory(*state_nonlinearities)
        if state_nonlinearities
        else None
    )

    return reference_pipeline, state_pipeline
